import test from 'node:test';import assert from 'node:assert/strict';
import {createQuota,QuotaConflict,QuotaExceeded,QuotaUnavailable,WINDOW,clientIp,hashIp}from'../lib/quota.mjs';
function memoryStore(){let version=0,state={version:1,entries:[]};return {async read(){return{state:structuredClone(state),etag:String(version)};},async write(next,etag){if(etag!==String(version))throw new QuotaConflict();state=structuredClone(next);version++;},state:()=>state};}
const options=now=>({now:()=>now,wait:async()=>{}});
test('shared state admits only three concurrent reservations for one IP',async()=>{const store=memoryStore(),now=Date.UTC(2026,9,2,12);const clients=[createQuota(store,options(now)),createQuota(store,options(now))];const results=await Promise.allSettled(Array.from({length:12},(_,i)=>clients[i%2].reserve('same-ip')));assert.equal(results.filter(r=>r.status==='fulfilled').length,3);assert.ok(results.filter(r=>r.status==='rejected').every(r=>r.reason instanceof QuotaExceeded&&r.reason.code==='ip_quota_exceeded'));assert.equal(store.state().entries.length,3);});
test('global quota stays at fifty under concurrent admissions from different IPs',async()=>{const store=memoryStore(),now=Date.UTC(2026,9,2,12),quota=createQuota(store,options(now));for(let i=0;i<45;i++)await quota.reserve('seed-'+i);const results=await Promise.allSettled(Array.from({length:20},(_,i)=>createQuota(store,options(now)).reserve('burst-'+i)));assert.equal(results.filter(r=>r.status==='fulfilled').length,5);assert.equal(store.state().entries.length,50);await assert.rejects(quota.reserve('another'),e=>e.code==='daily_quota_exceeded'&&e.retryAt==='2026-10-03T00:00:00.000Z');});
test('IP limits roll over twenty-four hours rather than resetting at midnight',async()=>{const store=memoryStore();let now=Date.UTC(2026,9,2,23,59);const quota=createQuota(store,{now:()=>now,wait:async()=>{}});for(let i=0;i<3;i++)await quota.reserve('ip');now=Date.UTC(2026,9,3,0,1);await assert.rejects(quota.reserve('ip'),e=>e.code==='ip_quota_exceeded');now=Date.UTC(2026,9,2,23,59)+WINDOW;assert.equal((await quota.reserve('ip')).remaining,2);});
test('daily quota resets at midnight UTC while preserving rolling IP history',async()=>{const store=memoryStore();let now=Date.UTC(2026,9,2,23,59);const quota=createQuota(store,{now:()=>now,wait:async()=>{}});for(let i=0;i<50;i++)await quota.reserve('ip-'+i);await assert.rejects(quota.reserve('new-ip'),QuotaExceeded);now=Date.UTC(2026,9,3);await quota.reserve('new-ip');assert.equal(store.state().entries.filter(e=>e.at===now).length,1);});
test('early upstream failure can release a reservation; unavailable storage fails closed',async()=>{const store=memoryStore(),quota=createQuota(store,options(Date.now()));const r=await quota.reserve('ip');await quota.release(r.id);assert.equal(store.state().entries.length,0);await assert.rejects(createQuota({read:async()=>{throw Error('offline');}}).reserve('ip'),QuotaUnavailable);await assert.rejects(createQuota({read:async()=>({state:{version:1,entries:[]},etag:'1'}),write:async()=>{throw Error('offline');}}).reserve('ip'),QuotaUnavailable);});
test('client identity comes from the edge header, normalizes IPv6, and stores salted hashes',()=>{assert.equal(clientIp({headers:{'x-forwarded-for':'2001:0db8:0:0:0:0:0:1','x-real-ip':'192.0.2.99'}}),'2001:db8::1');assert.throws(()=>clientIp({headers:{'x-real-ip':'192.0.2.99'}}),QuotaUnavailable);assert.notEqual(hashIp('192.0.2.1','salt-a'),hashIp('192.0.2.1','salt-b'));assert.match(hashIp('192.0.2.1','salt-a'),/^[a-f0-9]{64}$/);});
